### PR TITLE
#8 fix user create bug

### LINKED ISSUE #8: Can't create user
Getting this error while creating user:

{
    "timestamp": "2018-03-10T13:58:07.110+0000",
    "status": 403,
    "error": "Forbidden",
    "message": "Forbidden",
    "path": "/user"
}

### PR DESCRIPTION
**Pull request by vadzim-matsiuk**
fixed #8

### CODE REVIEW

**Comment by mikita-herasiutsin** [comment]
We have a new problem. For successful POST request we receive entity with all information including password, e.g:
{
    "id": 11,
    "username": "bob3",
    "password": "secret",
    "encryptedPassword": "$2a$10$oAIb1xYOPItDhZpp/pmYpOsIF2Qh/.4FKxmEsDiTdUQlnz4GRLuNS"
}

I suggest to change response to 201 (Created) with empty body

**Comment by mikita-herasiutsin** [comment]
Add integration tests for saving user

File: src/test/java/simplifier/UserControllerIT.java [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+  @Test
+  public void createUser() {
+   User user = new User();
+   user.setUsername("test");
+   user.setPassword("test");
+
+   ResponseEntity<User> responseEntity = restTemplate.postForEntity("/user",
+       user, User.class);
+
+   assertEquals(HttpStatus.CREATED, responseEntity.getStatusCode());
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: Use assertThat() in all tests and add checking for empty response body

File: src/test/java/simplifier/UserControllerIT.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+import org.springframework.boot.test.context.SpringBootTest;
+import org.springframework.boot.test.web.client.TestRestTemplate;
+import org.springframework.http.HttpStatus;
+import org.springframework.http.ResponseEntity;
+import org.springframework.test.context.junit4.SpringRunner;
+import simplifier.model.User;
+
+@RunWith(SpringRunner.class)
+@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT )
+public class UserControllerIT {
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: Delete another empty file for integration tests

File: src/test/java/simplifier/UserControllerIT.java [hunk 3]
```diff
@@ -36,6 +35,6 @@ public void createUser() {
        user, User.class);
 
    assertThat(HttpStatus.CREATED, is(responseEntity.getStatusCode()));
-   assertTrue(!responseEntity.hasBody());
+   assertThat(false, is(responseEntity.hasBody()));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: `assertThat(actual, expected)` but not` assertThat(expected, actual)`. Also `assertThat(responseEntity.getBody(), is(nullValue()))` seems more readable

File: src/test/java/simplifier/UserControllerIT.java [hunk 4]
```diff
@@ -34,7 +35,7 @@ public void createUser() {
    ResponseEntity<User> responseEntity = restTemplate.postForEntity("/user",
        user, User.class);
 
-   assertThat(HttpStatus.CREATED, is(responseEntity.getStatusCode()));
-   assertThat(false, is(responseEntity.hasBody()));
+   assertThat(responseEntity.getStatusCode(), is(HttpStatus.CREATED));
+   assertThat(responseEntity.getBody(), is(nullValue()));
   }
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: you need to check db that user is saved

File: src/test/java/simplifier/UserControllerIT.java [hunk 5]
```diff
@@ -35,6 +44,9 @@ public void createUser() {
    ResponseEntity<User> responseEntity = restTemplate.postForEntity("/user",
        user, User.class);
 
+   User savedUser = userRepository.findByUsername("test");
+
+   assertThat(savedUser, is(equalTo(user)));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: is(equalTo()) is redundant because is() calls equalTo()

File: src/main/java/simplifier/model/User.java [hunk 6]
```diff
@@ -53,4 +55,25 @@ public String getEncryptedPassword() {
...
+
+  @Override
+  public int hashCode() {
+    HashCodeBuilder hcb = new HashCodeBuilder();
+    hcb.append(username);
+    return hcb.toHashCode();
+  }
+
+  @Override
+  public boolean equals(Object obj) {
```
Comment (mikita-herasiutsin) [inline src/main/java/simplifier/model/User.java]: The problem is user with same username can be saved and then retrieving 2 users from repository with same usernames but different id and passwords will be equal

File: pom.xml [hunk 7]
```diff
@@ -63,7 +63,12 @@
 			<artifactId>spring-security-test</artifactId>
 			<scope>test</scope>
 		</dependency>
-	</dependencies>
+    <dependency>
+      <groupId>org.apache.commons</groupId>
+      <artifactId>commons-lang3</artifactId>
+      <version>3.4</version>
+    </dependency>
+  </dependencies>
```
Comment (mikita-herasiutsin) [inline pom.xml]: format this file

File: src/main/java/simplifier/services/UserServiceImpl.java [hunk 8]
```diff
@@ -25,7 +26,11 @@ public void setbCryptPasswordEncoder(
   }
 
   @Override
-  public User saveUser(User user) {
+  public User saveUser(User user) throws NameNotUniqueException{
+    User checkForUnique = userRepository.findByUsername(user.getUsername());
+    if (checkForUnique != null) {
+      throw new NameNotUniqueException();
```
Comment (mikita-herasiutsin) [inline src/main/java/simplifier/services/UserServiceImpl.java]: Change throwing exception to `Optional<User>` return type

File: src/main/java/simplifier/controllers/UserController.java [hunk 9]
```diff
@@ -23,9 +24,11 @@ public void setUserService(UserService userService) {
 
   @PostMapping
   public ResponseEntity<?> createUser(@RequestBody User user) {
-
-    userService.saveUser(user);
-
+    try {
+      userService.saveUser(user);
```
Comment (mikita-herasiutsin) [inline src/main/java/simplifier/controllers/UserController.java]: Remove try/catch. This type of design should be avoided

File: pom.xml (hunk 7 above)
Comment (mikita-herasiutsin) [reply pom.xml]: Replace tabs to spaces in all files

File: src/main/java/simplifier/services/UserServiceImpl.java [hunk 10]
```diff
@@ -26,12 +26,12 @@ public void setbCryptPasswordEncoder(
   }
 
   @Override
-  public User saveUser(User user) throws NameNotUniqueException{
+  public Optional<User> saveUser(User user) {
     User checkForUnique = userRepository.findByUsername(user.getUsername());
```
Comment (mikita-herasiutsin) [inline src/main/java/simplifier/services/UserServiceImpl.java]: Variable names should be noun but not verb. Change variable name to just user or foundUser

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 11]
```diff
@@ -36,12 +34,7 @@ public void saveUser() {
 
     when(userRepository.save(user)).thenReturn(user);
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: All cases should be covered by unit tests

File: src/main/java/simplifier/controllers/UserController.java [hunk 12]
```diff
@@ -24,11 +23,9 @@ public void setUserService(UserService userService) {
 
   @PostMapping
   public ResponseEntity<?> createUser(@RequestBody User user) {
-    try {
-      userService.saveUser(user);
-    } catch (NameNotUniqueException e) {
-      return ResponseEntity.status(HttpStatus.CONFLICT).body("Username already exists");
+    if (userService.saveUser(user).isPresent()) {
```
Comment (mikita-herasiutsin) [inline src/main/java/simplifier/controllers/UserController.java]: Use map()/orElse() methods instead of if()/isPresent()

File: src/test/java/simplifier/UserControllerIT.java [hunk 13]
```diff
@@ -16,37 +12,59 @@
...
+        assertThat(responseEntity.getBody(), is(nullValue()));
+    }
 
-  @Autowired
-  public void setRestTemplate(TestRestTemplate restTemplate) {
-    this.restTemplate = restTemplate;
-  }
+    @Test
+    public void conflictIfUsernameNotUnique() {
+        User firstUser = new User();
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: Use more meaningful names for variables, e.g. existingUser and another invalidUser

File: src/test/java/simplifier/UserControllerIT.java [hunk 14]
```diff
@@ -16,37 +12,59 @@
...
 
-   User savedUser = userRepository.findByUsername("test");
+        ResponseEntity<String> responseEntity = restTemplate.postForEntity("/user",
+                secondUser, String.class);
 
-   assertThat(savedUser, is(user));
-   assertThat(responseEntity.getStatusCode(), is(HttpStatus.CREATED));
-   assertThat(responseEntity.getBody(), is(nullValue()));
-  }
+        assertThat(responseEntity.getStatusCode(), is(HttpStatus.CONFLICT));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: Verifying that only one user is saved and response body has message are required

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 15]
```diff
@@ -16,28 +10,54 @@
...
-  @Mock
-  private BCryptPasswordEncoder bCryptPasswordEncoder;
+        verify(userRepository).save(user);
+    }
 
-  @InjectMocks
-  private UserServiceImpl userService;
+    @Test
+    public void doNotSaveIfUsernameDuplicate() {
+        User firstUser = new User();
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: Use more meaningful names

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 16]
```diff
@@ -16,28 +10,54 @@
...
+
+        when(userRepository.save(user)).thenReturn(user);
+
+        Optional<User> savedUser = userService.saveUser(user);
+
+        assertThat(savedUser, is(Optional.of(user)));
 
-  @Mock
-  private BCryptPasswordEncoder bCryptPasswordEncoder;
+        verify(userRepository).save(user);
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: You should verify that password was encoded

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 17]
```diff
@@ -16,28 +10,54 @@
...
 
-    User savedUser = userService.saveUser(user).get();
+        Optional<User> savedUser = userService.saveUser(secondUser);
 
-    assertThat(savedUser, is(user));
+        assertThat(savedUser, is(Optional.empty()));
 
-    verify(userRepository).save(user);
-  }
+        verify(userRepository).findByUsername(secondUser.getUsername());
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: You should verify that password encoding hasn't been invoked

File: src/test/java/simplifier/UserControllerIT.java [hunk 18]
```diff
@@ -0,0 +1,73 @@
...
+        User invalidUser = new User();
+        invalidUser.setUsername("test");
+        invalidUser.setPassword("test");
+
+        ResponseEntity<String> responseEntity = restTemplate.postForEntity("/user",
+                invalidUser, String.class);
+
+        assertThat(responseEntity.getStatusCode(), is(HttpStatus.CONFLICT));
+        assertThat(responseEntity.getBody(), is(notNullValue()));
+        assertThat(userRepository.findByUsername("test"), is(existingUser));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: You verify that found user is existing one but verification uses user's equals() method which compares usernames only. It means there can be 2 users with same usernames. This verification does not do what it should. I suggest to change equals()  to compare all fields

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 19]
```diff
@@ -17,28 +10,57 @@
...
 
-    User savedUser = userService.saveUser(user);
+        Optional<User> savedUser = userService.saveUser(invalidUser);
 
-    assertThat(savedUser, is(equalTo(user)));
+        assertThat(savedUser, is(Optional.empty()));
 
-    verify(userRepository).save(user);
-  }
+        verify(userRepository).findByUsername(invalidUser.getUsername());
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: Add verification that no more invocations of this mock are executed. It is possible to use save() method for example and test will pass, same is for bCryptPasswordEncoder. Use verifyNoMoreInteractions() in all tests or use should().then() instead of verify()

File: src/test/java/simplifier/UserControllerIT.java [hunk 20]
```diff
@@ -0,0 +1,73 @@
...
+
+        User invalidUser = new User();
+        invalidUser.setUsername("test");
+        invalidUser.setPassword("test");
+
+        ResponseEntity<String> responseEntity = restTemplate.postForEntity("/user",
+                invalidUser, String.class);
+
+        assertThat(responseEntity.getStatusCode(), is(HttpStatus.CONFLICT));
+        assertThat(responseEntity.getBody(), is(notNullValue()));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserControllerIT.java]: Verify that exactly message exists in body

File: src/test/java/simplifier/UserServiceImplTest.java [hunk 21]
```diff
@@ -1,13 +1,6 @@
 package simplifier;
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/UserServiceImplTest.java]: Move all tests to same packages that tests classes are in

File: src/test/java/simplifier/controllers/UserControllerIT.java [hunk 22]
```diff
@@ -57,7 +67,7 @@ public void conflictIfUsernameNotUnique() {
         existingUser.setUsername("test");
         existingUser.setPassword("test");
 
-        userRepository.save(existingUser);
+        Optional<User> savedUser = userService.saveUser(existingUser);
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/controllers/UserControllerIT.java]: Services are not used in tests. Use repository instead

File: src/test/java/simplifier/controllers/UserControllerIT.java [hunk 23]
```diff
@@ -46,7 +56,7 @@ public void createUser() {
 
         User savedUser = userRepository.findByUsername("username");
 
-        assertThat(savedUser, is(user));
+        assertThat(savedUser, is(notNullValue()));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/controllers/UserControllerIT.java]: Why did you change to noNullValue()?

File: src/test/java/simplifier/controllers/UserControllerIT.java [hunk 24]
```diff
@@ -0,0 +1,86 @@
...
+        invalidUser.setUsername("test");
+        invalidUser.setPassword("test");
+
+        ResponseEntity<String> responseEntity = restTemplate.postForEntity("/user",
+                invalidUser, String.class);
+
+        String requiredMessage = "Username already exists";
+
+        assertThat(responseEntity.getStatusCode(), is(HttpStatus.CONFLICT));
+        assertThat(responseEntity.getBody(), is(notNullValue()));
```
Comment (mikita-herasiutsin) [inline src/test/java/simplifier/controllers/UserControllerIT.java]: this is redundant line
